### ISSUE TITLE
Permission denied while saving ingame screenshot

### ISSUE THREAD

**Issue by OndroNR** [IceReaper/OpenKrush#144] opened 2021-03-21 12:40 UTC
Crashed whole game. I have no idea why it does not have permission here. It should fail softly at least.

```
OpenRA engine version 666566ca3a092e1e6d34d5979bbd4cde285b3ae7
OpenKrush Generation 1 mod version playtest-20210316
on map ba4281f7725c72c3c6e5c6f9e1cb10efdb6d9075 (Lost City by MrZuerg).
Date: 2021-03-21 12:33:38Z
Operating System: Windows (Microsoft Windows NT 10.0.19042.0)
Runtime Version: .NET CLR 5.0.4
Exception of type `System.UnauthorizedAccessException`: Access to the path 'C:\Users\Ondrej\Documents\OpenRA\Screenshots\openkrush_gen1\playtest-20210316\openkrush_gen1-2021-03-21T123337784Z.png' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by OndroNR** [comment] 2021-03-21 12:46
It works in stable release OpenRA.

**Comment by Dzierzan** [comment] 2021-03-21 12:48
Does this happen in the current playtest version or in the master branch?

**Comment by OndroNR** [comment] 2021-03-21 13:03
Current playtest. I don't have .NET environment setup on my windows machine, so I can't test master.

**Comment by IceReaper** [comment] 2021-03-21 19:35
Likely an openra bug. Ill test this

**Comment by IceReaper** [comment] 2021-08-19 09:29
Does this problem still persist? Or was that a local problem (maybe caused by the antivirus app?)

**Comment by OndroNR** [comment] 2021-09-17 13:04
Issue does persist with latest playtest, but it is caused by Avast Antivirus (I will try report this). OpenRA makes screenshots well. OpenKrush is very uncommon software, so probably some antivirus heuristics are causing this. Maybe OpenKrush at least should not crash during gameplay even without saved screenshot?

```OpenRA engine version 6c5100336bfc0b866b59cb754ff4e2d2718dd1f9
OpenKrush Generation 1 mod version playtest-20210813
on map 0944189b3aa63c94cc9815d3d4e4779b8ec3ddf6 (Shellmap by OpenKrush Team).
Date: 2021-09-17 12:57:39Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 5.0.9
Exception of type `System.UnauthorizedAccessException`: Access to the path 'C:\Users\Ondrej\Documents\OpenRA\Screenshots\openkrush_gen1\playtest-20210813\openkrush_gen1-2021-09-17T125739002Z.png' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by IceReaper** [comment] 2022-02-21 17:38
Im closing this. Not crashing - sure should be an openra thing. However the cause is a third party software, so there is nothing i can do about this in openkrush. If it persists, this should be re-opened on the openra issue tracker.

**Closed by IceReaper** 2022-02-21 17:38 UTC
Labels: Bug, Crash
